# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-19 17:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text=b'First name', max_length=100, verbose_name=b'First name')),
                ('last_name', models.CharField(help_text=b'Last name', max_length=100, verbose_name=b'Last name')),
                ('email_address', models.CharField(help_text=b'Email Address', max_length=100, verbose_name=b'Email Address')),
                ('gender', models.CharField(choices=[(b'male', b'Male'), (b'female', b'Female')], default=b'male', help_text=b'Gender: Male or Female', max_length=10, verbose_name=b'Gender')),
                ('salary', models.IntegerField()),
                ('designation', models.CharField(help_text=b'Designation', max_length=100, verbose_name=b'Designation')),
                ('profile', models.ImageField(upload_to=b'profile', verbose_name=b'profile')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text=b'Date when employee created.', verbose_name=b'Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text=b'Date when employee updated.', verbose_name=b'Updated At')),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
            },
        ),
    ]
